#!/usr/bin/env ansible-playbook
---

# before install.
- name: Install requires package for apt module
  become: true
  apt:
    name: python-apt

- block:

  - name: Add third-party repository on Debian
    become: true
    apt_repository:
      repo: "deb {{ debian_php7_apt_repo }} {{ ansible_distribution_release }} all"
    when:
      - ansible_distribution|lower == "debian"
      - ansible_distribution_major_version < "9"

  - name: Add apt key on Debian
    become: true
    apt_key:
      url: "{{ debian_php7_apt_key }}"
    when:
      - ansible_distribution|lower == "debian"
      - ansible_distribution_major_version < "9"

  - name: Add third-party repository on Ubuntu
    become: true
    apt_repository:
      repo: "{{ ubuntu_php7_ppa_repo }}"
    when:
      - ansible_distribution|lower == "ubuntu"

  when: apt_php_third_party_repo == true

# Update apt cache.
- name: Update apt cache
  become: true
  apt: update_cache=true

# Install PHP7 packages.
- name: Install php packages
  become: true
  apt:
    name: "{{ item }}"
  with_nested: "{{ apt_php_packages }}"
  when: apt_php_packages is defined
  notify:
    - restart php7-fpm

- name: Start php7-fpm
  become: true
  service:
    name: "php{{ apt_php_version }}-fpm"
    state: started
    enabled: yes

# vim: ft=ansible :
